# OUTPUT_LANG_INDEX start from 0
generator-localization:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=15vyWB1dUlyg8I-9MMqAQN3lSg_K8oqVuvfPYzpZbpC0 GID_ID=Sheet1 OUTPUT_FOLDER=../public/locales/en/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=15vyWB1dUlyg8I-9MMqAQN3lSg_K8oqVuvfPYzpZbpC0 GID_ID=Sheet1 OUTPUT_FOLDER=../public/locales/jp/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=5 SPREADSHEET_ID=15vyWB1dUlyg8I-9MMqAQN3lSg_K8oqVuvfPYzpZbpC0 GID_ID=Sheet1 OUTPUT_FOLDER=../public/locales/ch/common.json
	
